### ISSUE TITLE
Shouldn't export `greet`

### ISSUE THREAD

**Issue by SyxP** [azeredo-e/BrazilCentralBank.jl#2]
In my opinion, you shouldn't need to export `greet` in this package. (You can of course do whatever you want)

https://github.com/azeredo-e/BrazilCentralBank.jl/blob/71907424c57cc77d551b415a2880fb6a8d9a73f8/src/BrazilCentralBank.jl#L15

**Comment by azeredo-e** [comment]
I thought it was a fun little thing to left on, but yeah, I guess I should not export and just left for access directly through calling the name of the module.

I'm removing the export.

Thanks for the advice!
